default: &default
  adapter: mysql2
  username: root
  password: 1
  host: localhost

development:
  <<: *default
  database: purr_blog

production:
  <<: *default
  database: ENV['DATABASE_URL']
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORDs']
